changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputFileEncoding=UTF-8
referenceUrl=hibernate:spring:fr.avenirsesr.portfolio.security.accesscontrol.infrastructure.adapter.model,\
  fr.avenirsesr.portfolio.security.authentication.infrastructure.adapter.model,\
  fr.avenirsesr.portfolio.security.principal.infrastructure.adapter.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
url=jdbc:postgresql://localhost:65432/avenirs_access_control
username=avenirs_security_admin
password=ENC(nrhrW8giUqCjQzWRBDVj/XYVStp8Tgxs)
driver=org.postgresql.Driver
defaultSchemaName=dev
liquibaseSchemaName=dev
