name: "Publish Javadoc and Jacoco Reports"
description: "Publish the Javadoc and coverage reports to GitHub Pages using peaceiris/actions-gh-pages@v4"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  publish_dir:
    description: "Directory to publish"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Publish Javadoc and Jacoco Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ inputs.publish_dir }}
