name: "Publish javadoc and Jacoco reports"
description: "Publish the javadoc and coverage reports to gh pages"

inputs:
  github_token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish Javadoc and Jacoco Report to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mkdir -p output
        cp -r target/site/apidocs output/javadoc
        cp -r target/site/jacoco output/jacoco

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git clone --branch=gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
        cd gh-pages

        rm -rf javadoc jacoco
        cp -r ../output/javadoc .
        cp -r ../output/jacoco .

        git add .
        git commit -m "Update Javadoc and Jacoco reports"
        git push origin gh-pages
      shell: bash
