name: "Publish javadoc and Jacoco reports"
description: "Publish the javadoc and coverage rports to gh pages"

runs:
  using: "composite"
  steps:       
    - name: Publish Javadoc and Jacoco Report to GitHub Pages
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          # Create a directory to store the Javadoc and Jacoco reports
          mkdir -p output
          
          # Copy Javadoc
          cp -r target/site/apidocs output/javadoc
          
          # Copy Jacoco report
          cp -r target/site/jacoco output/jacoco

          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone the gh-pages branch
          git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages

          # Clean old reports and copy new ones
          rm -rf javadoc jacoco
          cp -r ../output/javadoc .
          cp -r ../output/jacoco .

          # Commit and push changes
          git add .
          git commit -m "Update Javadoc and Jacoco reports"
          git push
      shell: bash 
