name: "Setup PostgreSQL"
description: "Initializes PostgreSQL"

runs:
  using: "composite"
  steps:
    - name: Pull PostgreSQL Image
      run: |
        echo "Pulling PostgreSQL Docker image..."
        docker pull postgres:latest
      shell: bash

    - name: Start PostgreSQL Container
      run: |
        echo "Starting PostgreSQL Docker container..."
        docker run -d --name avenirs-postgres \
          --network avenirs-network \
          -e POSTGRES_USER=$POSTGRES_USER \
          -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
          -e POSTGRES_DB=$POSTGRES_DB \
          -p 65432:5432 \
          postgres:latest
      shell: bash

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        for i in {1..4}; do
          if docker exec avenirs-postgres pg_isready -U $POSTGRES_USER -h localhost -p 5432; then
            echo "PostgreSQL is ready."
            break
          fi
          echo "PostgreSQL is not ready yet... retrying in 5 seconds."
          sleep 5
        done
      shell: bash 

    - name: Initialize Database
      run: |
        echo "Injecting init-db.sql into PostgreSQL..."
        docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /src/main/resources/db/init-db.sql
        echo "Injecting init-test-db.sql into PostgreSQL..."
        docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /src/test/resources/db/init-test-db.sql
      shell: bash
