name: "Setup OpenLDAP"
description: "Initializes OpenLDAP environment"

runs:
  using: "composite"
  steps:
    - name: Cache Docker Images for OpenLDAP
      uses: actions/cache@v4
      with:
        path: /tmp/.docker-cache-openldap
        key: docker-openldap-cache
        restore-keys: |
          docker-openldap-

    - name: Ensure Cache Directory Exists
      run: |
        mkdir -p /tmp/.docker-cache-openldap
        echo "Cache directory ensured: /tmp/.docker-cache-openldap"
      shell: bash

    - name: Load OpenLDAP Image from Cache
      run: |
        if [ -f /tmp/.docker-cache-openldap/openldap.tar ]; then
          echo "Loading OpenLDAP image from cache..."
          docker load -i /tmp/.docker-cache-openldap/openldap.tar
          echo "OpenLDAP image loaded from cache."
        else
          echo "No cached OpenLDAP image found."
        fi
      shell: bash

    - name: Check for Updates or Missing OpenLDAP Image
      run: |
        LOCAL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' osixia/openldap:latest 2>/dev/null || echo "none")
        REMOTE_DIGEST=$(docker manifest inspect osixia/openldap:latest | jq -r '.manifests[0].digest' 2>/dev/null || echo "none")
        echo "Local Digest: $LOCAL_DIGEST"
        echo "Remote Digest: $REMOTE_DIGEST"
        if [ "$LOCAL_DIGEST" != "$REMOTE_DIGEST" ] || [ "$LOCAL_DIGEST" == "none" ]; then
          echo "Pulling updated OpenLDAP Docker image..."
          docker pull osixia/openldap:latest
          docker save osixia/openldap:latest -o /tmp/.docker-cache-openldap/openldap.tar
          echo "OpenLDAP image pulled and saved to cache."
        else
          echo "OpenLDAP image is up-to-date and loaded from cache."
        fi
      shell: bash

    - name: Verify Image Loaded from Cache
      run: |
        if docker image inspect osixia/openldap:latest > /dev/null 2>&1; then
          echo "OpenLDAP image successfully loaded from cache and available as 'osixia/openldap:latest'."
        else
          echo "OpenLDAP image not found after loading. Check the load step."
          exit 1
        fi
      shell: bash

    - name: Start OpenLDAP Container
      run: |
        docker run -d --name avenirs-openldap \
        --network avenirs-network \
        -e LDAP_ORGANISATION="avenirs-esr.fr" \
        -e LDAP_DOMAIN="ldap-dev.avenirs-esr.fr" \
        -e LDAP_ADMIN_PASSWORD=$LDAP_ADMIN_PASSWORD \
        -e LDAP_BASE_DN=$LDAP_BASE_DN \
        -e LDAP_REMOVE_CONFIG_AFTER_SETUP="false" \
        -p 389:389 -p 636:636 \
        --env LDAP_TLS_VERIFY_CLIENT=never \
        --env LDAP_LOG_LEVEL=256 \
        osixia/openldap:latest
      shell: bash

    - name: Copy LDIF File to Container
      run: docker cp .github/ldap/openldap-fixtures.ldif avenirs-openldap:/tmp/openldap-fixtures.ldif
      shell: bash

    - name: Wait for OpenLDAP to be ready
      run: |
        echo "Waiting for OpenLDAP to be ready..."
        for i in {1..10}; do
          if docker exec avenirs-openldap ldapsearch -x -H ldap://localhost:389 -D "$LDAP_ADMIN" -w $LDAP_ADMIN_PASSWORD -b $LDAP_BASE_DN -s base "(objectclass=*)" > /dev/null 2>&1; then
            echo "OpenLDAP is ready."
            break
          fi
          echo "OpenLDAP is not ready yet... retrying in 5 seconds."
          sleep 5
        done
      shell: bash

    - name: Inject LDIF into LDAP
      run: |
        docker exec avenirs-openldap ldapadd -x -D "$LDAP_ADMIN" -w $LDAP_ADMIN_PASSWORD -f /tmp/openldap-fixtures.ldif
      shell: bash
