name: "Load tests"
description: "Executes load test"

runs:
  using: "composite"
  steps:
    - name: Load Test Data
      run: |
        echo "Loading test data..."
        psql -h localhost -p 65432  -U $POSTGRES_USER -d $POSTGRES_DB -f src/test/resources/db/load-test-fixtures.sql


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    - name: Run Locust Load Test
      run: |
        locust -f locustfile.py --host=$AVENIRS_APP_URL --headless -u 100 -r 10 --run-time 1m --html ./target/site/locust_report.html


    - name: Upload Locust report
      uses: actions/upload-artifact@v4
      with:
        name: locust-report
        path: ./target/site/locust_report.html

