name: "Load tests"
description: "Executes load test with locust"
inputs:
  host:
    description: "Host to test"
    required: true
  fixtures:
    description: "Fixtures sql file"
    required: true
  locustfile:
    description: "Locust file name"
    required: false
    default: "locustfile.py"
  locust_report:
    description: "Locust report file"
    required: false
    default: "./target/site/locust_report.html"

  locust_csv_reports:
    description: "Locust csv reports base name"
    required: false
    default: "./target/site/locust_report"

  locust_duration:
      description: "Duration of the test"
      required: false
      default: "1m"

  locust_users:
      description: "Number of users for the load test"
      required: false
      default: "100"

  locust_ramp_rate:
      description: "User ramp rate"
      required: false
      default: "10"

runs:
  using: "composite"
  steps:
    - name: Load Test Data
      run: |
        echo "Loading test data..."
        psql -h localhost -p 65432  -U $POSTGRES_USER -d $POSTGRES_DB -f ${{ inputs.fixtures }}
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust
      shell: bash

    - name: Run Locust Load Test
      run: |
        locust -f ${{env.locustfile}} \
          --host=${{env.host}} \
          --headless \
          -u ${{env.locust_users}} \
          -r ${{env.locust_ramp_rate }} \
          --run-time ${{env.locust_duration}} \
          --html ${{env.locust_report}} \
          --csv ${{env.locust_csv_reports}}

      shell: bash

    - name: Upload Locust report
      uses: actions/upload-artifact@v4
      with:
        name: locust-report
        path: |
          ./target/site/locust_report.html
          ./target/site/locust_report_stats.csv
          ./target/site/locust_report_failures.csv


