name: "Run Tests"
description: "Compiles and runs Spring tests"

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
            distribution: 'temurin'
            java-version: '21'
    
    - name: Add avenirs-apache to /etc/hosts
      run: |
        echo "127.0.0.1 avenirs-apache" | sudo tee -a /etc/hosts
      shell: bash
            
    - name: Generate env.properties to Ignore SSL Verification
      run: |
        echo "spring.security.oauth2.client.registration.custom-client-provider.provider.ssl-verification=false" > src/main/resources/env.properties
        echo "spring.ssl.ignore=true" >> src/main/resources/env.properties
        echo "spring.cloud.openfeign.ssl.skip-ssl-validation=true" >> src/main/resources/env.properties
        echo "server.ssl.enabled=false" >> src/main/resources/env.properties
      shell: bash


    - name: Build and Test
      run: |
        ./mvnw clean compile javadoc:javadoc test jacoco:report
      shell: bash 
