name: "Run Tests"
description: "Compiles and runs Spring tests"

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
            distribution: 'temurin'
            java-version: '21'

    - name: Build and Test
      run: |
        ./mvnw clean compile javadoc:javadoc -DskipTests
      shell: bash 
