name: Deploy on dev server
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  call-main-ci:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/deploy-workflow.yaml@main
    secrets: inherit
