name: Develop to Main Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  call-main-ci:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/only-develop-to-main-workflow.yaml@main
    secrets: inherit
