name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env: 
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_BASE_DN: ${{ secrets.LDAP_BASE_DN }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 65432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PostgreSQL
        uses: ./.github/actions/setup-postgres

      - name: Copy CAS and LDAP Files to /tmp
        run: |
          sudo cp -r --preserve=all .github/cas/* /tmp/
          sudo cp -r --preserve=all .github/ldap/* /tmp/

      - name: Pull CAS Image
        run: docker pull apereo/cas:6.6.15.2

      - name: Pull OpenLDAP Image
        run: docker pull osixia/openldap:latest

      - name: Start CAS Container
        run: |
          docker run -d --name avenirs-cas  \
          -v /tmp:/etc/cas:rw \
          -p 443:8443 -p 8080:8080 apereo/cas:6.6.15.2

      - name: Start OpenLDAP Container
        run: |
          docker run -d --name openldap \
          -e LDAP_ORGANISATION="avenirs-esr.fr" \
          -e LDAP_DOMAIN="ldap-dev.avenirs-esr.fr" \
          -e LDAP_ADMIN_PASSWORD=$LDAP_ADMIN_PASSWORD \
          -e LDAP_BASE_DN=$LDAP_BASE_DN \
          -e LDAP_REMOVE_CONFIG_AFTER_SETUP="false" \
          -p 389:389 -p 636:636 \
          --env LDAP_TLS_VERIFY_CLIENT=never \
          --env LDAP_LOG_LEVEL=256 \
          --volume /tmp/openldap-fixtures.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/my-custom.ldif:ro \
          osixia/openldap:latest

      - name: Wait for CAS to be ready
        run: |
         echo "Waiting for CAS to be ready..."
         for i in {1..10}; do
          STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost/cas/login)
          if [ "$STATUS" -eq 200 ]; then
            echo "CAS is ready."
            break
          fi
          echo "CAS is not ready yet... retrying in 5 seconds. Current status: $STATUS"
          sleep 5
         done
        

      - name: Display CAS Startup Logs
        run: docker logs avenirs-cas

      - name: Test CAS Accessibility Inside Container
        run: docker exec avenirs-cas curl -v -k https://localhost:8443/cas/login

      - name: Test CAS Accessibility Outside Container
        run: curl -v -k https://localhost:443/cas/login
      
      - name: Install LDAP Utilities and Test LDAP Connection
        run: |
          sudo apt-get update && sudo apt-get install -y ldap-utils
          ldapsearch -x -H ldap://localhost:389 -D "cn=admin,dc=ldap-dev,dc=avenirs-esr,dc=fr" -w admin -b "dc=ldap-dev,dc=avenirs-esr,dc=fr" "(uid=paterson)"


      - name: Run Tests
        uses: ./.github/actions/run-tests
        if: false
        
      - name: Display cas logs after tests
        if: always()  
        run: |
          docker logs avenirs-cas
