name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-setup-postgres:
    uses: ./.github/workflows/setup-postgres.yml
    with:
      postgres_user: ${{ secrets.POSTGRES_USER }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
      postgres_db: ${{ secrets.POSTGRES_DB }}
