name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-setup-postgres:
    uses: ./.github/workflows/setup-postgres.yaml
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}