name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  avenir-portfolio-security:
    runs-on: ubuntu-latest
    env:
      ENABLE_POSTGRES_ACTION: true
      ENABLE_OPENLDAP_ACTION: true
      ENABLE_CAS_ACTION: true
      ENABLE_UNIT_TESTS_ACTION: true
      ENABLE_START_APP_ACTION: true
      ENABLE_FIXTURES_ACTION: true
      ENABLE_LOAD_TESTS_ACTION: true
      ENABLE_PUBLISH_ACTION: true
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_ADMIN: ${{ secrets.LDAP_ADMIN }}
      LDAP_BASE_DN: ${{ secrets.LDAP_BASE_DN }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      AVENIRS_APP_URL: http://localhost:12000
      AVENIRS_LOAD_TESTS_FIXTURES: src/test/resources/db/load-test-fixtures.sql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create avenirs-network

      - name: Setup Postgresql
        if: ${{env.ENABLE_POSTGRES_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/setup-postgres@main
        with:
          jasypt_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
          postgres_db: ${{secrets.POSTGRES_DB}}
          postgres_user: ${{secrets.POSTGRES_USER}}
          postgres_password: ${{secrets.POSTGRES_PASSWORD}}

      - name: Stop workflow after postgres
        uses: avenirs-esr/avenirs-workflows/.github/actions/gh-action-utils/stop-workflow@main
        with:
          disabled: true

      - name: Setup OpenLDAP
        if: ${{env.ENABLE_OPENLDAP_ACTION=='true'}}
        uses: avenirs-esr/avenirs-workflows/.github/actions/setup-openldap@main
        with:
          ldap_base_dn: ${{env.LDAP_BASE_DN}}
          ldap_admin: ${{env.LDAP_ADMIN}}
          ldap_admin_password: ${{env.LDAP_ADMIN_PASSWORD}}
          ldap_fixtures: .github/fixtures/openldap-fixtures.ldif
          disable_fixtures: false

      - name: Setup CAS
        if: ${{env.ENABLE_CAS_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/setup-cas@main
        with:
          rebuild: false

      - name: (DEBUG) Check Docker containers
        if : false
        run: docker ps -a

      - name: Unit tests and code coverage
        if: ${{env.ENABLE_UNIT_TESTS_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/unit-tests-and-code-coverage@main

      - name: (DEBUG) Display cas logs after tests
        if: false
        run: |
          docker logs avenirs-cas

      - name: Start application
        if: ${{env.ENABLE_START_APP_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/spring-boot-app/start@main
        with:
          app_url: $AVENIRS_APP_URL

      - name: Fixtures
        if: ${{env.ENABLE_FIXTURES_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/fixtures/faker@main
        with:
          ldap_admin: ${{env.LDAP_ADMIN}}
          ldap_admin_password: ${{env.LDAP_ADMIN_PASSWORD}}

      - name: Load Tests
        if: ${{env.ENABLE_LOAD_TESTS_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/load-tests@main
        with:
          fixtures: $AVENIRS_LOAD_TESTS_FIXTURES
          app_url: $AVENIRS_APP_URL

      - name: Stop application
        if: ${{env.ENABLE_LOAD_TESTS_ACTION == 'true' }}
        uses: avenirs-esr/avenirs-workflows/.github/actions/spring-boot-app/stop@main
        with:
          app_url: $AVENIRS_APP_URL

  call-common-workflow:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/common-backend.yml@main
    needs: avenir-portfolio-security
    with:
      run_lint: true
      run_security_scan: true
      run_test_coverage: false
      page_title: "Avenirs Portfolio Security"
    secrets: inherit
