name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env: 
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_ADMIN: ${{ secrets.LDAP_ADMIN }}
      LDAP_BASE_DN: ${{ secrets.LDAP_BASE_DN }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Docker network
        run: docker network create avenirs-network
        
      - name: Setup PostgreSQL
        uses: ./.github/actions/setup-postgres
      
      - name: Setup OpenLDAP
        uses: ./.github/actions/setup-openldap

      - name: Setup CAS
        uses: ./.github/actions/setup-cas
        with:
          rebuild: false

      - name: (DEBUG) Check Docker containers
        if : false
        run: docker ps -a
        
  
      - name: Run Tests
        uses: ./.github/actions/run-tests
        if: true
        
      - name: (DEBUG) Display cas logs after tests
        if: false  
        run: |
          docker logs avenirs-cas

      - name: Start Spring Boot Application
        run: |
          ./mvnw spring-boot:run &
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Wait for Application to Start
        run: |
          until curl --silent --fail http://localhost:8080/actuator/health; do
            echo "Waiting for the application to start..."
            sleep 5
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Install dependencies
        run: |
                python -m pip install --upgrade pip
                pip install locust

      - name: Run Locust Load Test
        run: |
                locust -f locustfile.py --host=http://localhost:12000 --headless -u 100 -r 10 --run-time 1m --html locust_report.html
              

      - name: Upload Locust report
        uses: actions/upload-artifact@v4
        with:
            name: locust-report
            path: locust_report.html

      - name: Stop Spring Boot Application
        run: |
            pkill -f 'java -jar' || pkill -f 'org.springframework.boot.loader.JarLauncher'
      

      - name: Publish reports
        uses: ./.github/actions/publish-to-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
        if: true
