name: Debug POSTGRES_USER Secret

on:
  push:
    branches:
      - main

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    environment:
      name: avenirs_ci  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug POSTGRES_USER Secret
        run: |
          if [ -z "${POSTGRES_USER}" ]; then
            echo "POSTGRES_USER is not set"
          else
            echo "POSTGRES_USER is set: ${POSTGRES_USER}"
          fi
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
