name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-setup-postgres:
    uses: ./.github/workflows/setup-postgres.yaml
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  call-setup-spring:
    uses: ./.github/workflows/setup-spring.yaml
    secrets:
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}