name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env: 
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 65432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      openldap:
        image: osixia/openldap:latest
        env:
          LDAP_ORGANISATION: "avenirs-esr.fr"
          LDAP_DOMAIN: "ldap-dev.avenirs-esr.fr"
          LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
          LDAP_BASE_DN: ${{secrets.LDAP_BASE_DN}}
          LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
        ports:
          - 389:389
          - 636:636
        options: >-
          --env LDAP_TLS_VERIFY_CLIENT=never
          --env LDAP_LOG_LEVEL=256
          --volume ${{ github.workspace }}/.github/ldap/openldap-fixtures.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/my-custom.ldif:ro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PostgreSQL
        uses: ./.github/actions/setup-postgres
     
      - name: Run Tests
        uses: ./.github/actions/run-tests

