name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-setup-postgres:
    uses: ./.github/workflows/setup-postgres.yaml
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}