name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  avenir-portfolio-security:
    runs-on: ubuntu-latest
    env:
      ENABLE_POSTGRES_ACTION: true
      ENABLE_OPENLDAP_ACTION: false
      ENABLE_CAS_ACTION: false
      ENABLE_UNIT_TESTS_ACTION: false
      ENABLE_LOAD_TESTS_ACTION: false
      ENABLE_PUBLISH_ACTION: false
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_ADMIN: ${{ secrets.LDAP_ADMIN }}
      LDAP_BASE_DN: ${{ secrets.LDAP_BASE_DN }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      AVENIRS_APP_URL: http://localhost:12000
      AVENIRS_LOAD_TESTS_FIXTURES: src/test/resources/db/load-test-fixtures.sql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Docker network
        run: docker network create avenirs-network

      - name: Setup Postgresql
        if: ${{env.ENABLE_POSTGRES_ACTION == 'true' }}
        uses: ./.github/actions/setup-postgres
        with:
          jasypt_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
          postgres_db: ${{secrets.POSTGRES_DB}}
          postgres_user: ${{secrets.POSTGRES_USER}}
          postgres_password: ${{secrets.POSTGRES_PASSWORD}}

      - name: Stop workflow after postgres
        uses: ./.github/actions/gh-action-utils/stop-workflow
        with:
          disabled: true

      - name: Setup OpenLDAP
        if: ${{env.ENABLE_OPENLDAP_ACTION=='true'}}
        uses: ./.github/actions/setup-openldap
        with:
          ldap_base_dn: ${{env.LDAP_BASE_DN}}
          ldap_admin: ${{env.LDAP_ADMIN}}
          ldap_admin_password: ${{env.LDAP_ADMIN_PASSWORD}}

      - name: Setup CAS
        if: ${{env.ENABLE_CAS_ACTION == 'true' }}
        uses: ./.github/actions/setup-cas
        with:
          rebuild: false

      - name: (DEBUG) Check Docker containers
        if : false
        run: docker ps -a

      - name: Unit and coverage Tests
        if: ${{env.ENABLE_UNIT_TESTS_ACTION == 'true' }}
        uses: ./.github/actions/unit-and-coverage-tests

      - name: (DEBUG) Display cas logs after tests
        if: false  
        run: |
          docker logs avenirs-cas

      - name: Start application
        if: ${{env.ENABLE_LOAD_TESTS_ACTION == 'true' }}
        uses: ./.github/actions/spring-boot-app/start
        with:
          app_url: $AVENIRS_APP_URL


      - name: Load Tests
        if: ${{env.ENABLE_LOAD_TESTS_ACTION == 'true' }}
        uses: ./.github/actions/load-tests
        with:
          fixtures: $AVENIRS_LOAD_TESTS_FIXTURES
          app_url: $AVENIRS_APP_URL

      - name: Stop application
        if: ${{env.ENABLE_LOAD_TESTS_ACTION == 'true' }}
        uses: ./.github/actions/spring-boot-app/stop
        with:
          app_url: $AVENIRS_APP_URL

      - name: Publish reports
        if: ${{env.ENABLE_PUBLISH_ACTION == 'true' }}
        uses: ./.github/actions/publish-to-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
