name: Debug and Setup PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if POSTGRES_USER Secret is Set
        run: |
          if [ -z "${POSTGRES_USER}" ]; then
            echo "POSTGRES_USER is not set or empty."
          else
            echo "POSTGRES_USER is set and masked for security."
          fi
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

  setup-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 65432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
