name: Postgres
on:
  workflow_call:
    inputs: {}

jobs:
  setup-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 65432:5432
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpassword
          POSTGRES_DB: avenirs_access_control
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SQL initialization script
        env:
          PGPASSWORD: pgpassword
        run: |
            psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d mydatabase -p 65432 -f src/test/resources/db/init-test-db.sql

